// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ6-zNrVUiuw5TOyQF5xR2Ec6VnIFW_rU',
    appId: '1:66931179496:web:6f4b88f79d4664aa3fee5d',
    messagingSenderId: '66931179496',
    projectId: 'timebanking-a4806',
    authDomain: 'timebanking-a4806.firebaseapp.com',
    storageBucket: 'timebanking-a4806.firebasestorage.app',
    measurementId: 'G-8H1QBFF151',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWBP2X-i-asJq2MAxiPShq9YTfNUcHuRA',
    appId: '1:66931179496:android:b1da4cc4ea63ce013fee5d',
    messagingSenderId: '66931179496',
    projectId: 'timebanking-a4806',
    storageBucket: 'timebanking-a4806.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnbsBP5OeyZgEnrEMOYelXb5rlQqsR8TY',
    appId: '1:66931179496:ios:0869fc835b6495643fee5d',
    messagingSenderId: '66931179496',
    projectId: 'timebanking-a4806',
    storageBucket: 'timebanking-a4806.firebasestorage.app',
    iosBundleId: 'com.example.aiforgood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnbsBP5OeyZgEnrEMOYelXb5rlQqsR8TY',
    appId: '1:66931179496:ios:0869fc835b6495643fee5d',
    messagingSenderId: '66931179496',
    projectId: 'timebanking-a4806',
    storageBucket: 'timebanking-a4806.firebasestorage.app',
    iosBundleId: 'com.example.aiforgood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ6-zNrVUiuw5TOyQF5xR2Ec6VnIFW_rU',
    appId: '1:66931179496:web:8917f227a7e292ce3fee5d',
    messagingSenderId: '66931179496',
    projectId: 'timebanking-a4806',
    authDomain: 'timebanking-a4806.firebaseapp.com',
    storageBucket: 'timebanking-a4806.firebasestorage.app',
    measurementId: 'G-L84EQX9XZJ',
  );
}
